site_id: dubizzle-UAE
display_name: Dubizzle United Arab Emirates
website: https://uae.dubizzle.com/
country: United Arab Emirates
github_username1: devops5796-netizen
github_username2: Dev545989
github_username3: work59
repo1: DUAE
repo2: D
repo3: duae
r2_prefix: DUAE 